# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
use_frameworks!

target 'NyTimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nytimes

    pod 'Alamofire', '~> 4.7'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 4.0'
end
