# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
use_frameworks!

target 'NyTimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nytimes

    pod 'Alamofire', '~> 4.7'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 4.0'
end

target :'NyTimesTests' do
    pod 'Alamofire', '~> 4.7'
    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 4.0'
end

post_install do |pi|
    pi.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            unless pi.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NO_USE_FRAMEWORKS=1'
            end
        end
    end
end
